// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB4OlNvA-j02-7W_cf10Z6ein4iRQMzGw',
    appId: '1:203519858181:web:dfc8318f031a38277a6e6c',
    messagingSenderId: '203519858181',
    projectId: 'messengerapp-6958b',
    authDomain: 'messengerapp-6958b.firebaseapp.com',
    storageBucket: 'messengerapp-6958b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNU8NvR4GFlDAIQ6q5r1T3CcgCQI9chU',
    appId: '1:203519858181:android:2ed6e89ad762ddd67a6e6c',
    messagingSenderId: '203519858181',
    projectId: 'messengerapp-6958b',
    storageBucket: 'messengerapp-6958b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbOSCTt0TaPX1KN-EGJKwte1rK76nblY8',
    appId: '1:203519858181:ios:0c0cc22ab03145cc7a6e6c',
    messagingSenderId: '203519858181',
    projectId: 'messengerapp-6958b',
    storageBucket: 'messengerapp-6958b.appspot.com',
    iosBundleId: 'kz.nagmet.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbOSCTt0TaPX1KN-EGJKwte1rK76nblY8',
    appId: '1:203519858181:ios:0c0cc22ab03145cc7a6e6c',
    messagingSenderId: '203519858181',
    projectId: 'messengerapp-6958b',
    storageBucket: 'messengerapp-6958b.appspot.com',
    iosBundleId: 'kz.nagmet.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB4OlNvA-j02-7W_cf10Z6ein4iRQMzGw',
    appId: '1:203519858181:web:0f1c366ce95c6f227a6e6c',
    messagingSenderId: '203519858181',
    projectId: 'messengerapp-6958b',
    authDomain: 'messengerapp-6958b.firebaseapp.com',
    storageBucket: 'messengerapp-6958b.appspot.com',
  );
}
